fix missing lifetime on trait in lifetime-generate
fixes this issue:

```rust
error: implicit elided lifetime not allowed here
  --> assoc_type_bound.rs:11:9
   |
11 | struct S { }
   |         ^
```

for

```rust
trait T<'a> { type X; }
struct S { }
impl<'a> T<'a> for S { type X = u8; }
```

which produced:

```rust
impl<'a24_a, > T22_T for D26_S {
    type A25_X = u8;
}
```

and now produces:

```rust
impl<'a24_a, > T22_T<'a24_a, > for D26_S {
    type A25_X = u8;
}
```